// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcxbpfkfnhhmaoltqlmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjeGJwZmtmbmhobWFvbHRxbG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTc0NzUsImV4cCI6MjA2NzM5MzQ3NX0.05VfI8QLj6Ymef5I7_gHqd7LjlGO8V7Lix4XaMAUNpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});